/**
 * withSeoulApiCleartext — Android cleartext(HTTP) exception scoped to the two
 * Seoul Open API hosts.
 *
 * Why this exists:
 * - 서울 실시간 지하철 API(`swopenapi.seoul.go.kr` / `openapi.seoul.go.kr`)는
 *   HTTPS를 제공하지 않는다(TLS 연결 자체가 실패). 호출은 평문 HTTP만 가능하다.
 * - Android 9(API 28)+ 는 평문 HTTP를 기본 차단하므로, 예외가 없으면 앱의 모든
 *   서울 API 호출이 즉시 거부된다(실시간 도착·길안내·즐겨찾기 전면 실패).
 * - iOS 쪽은 이미 `app.json`의 `ios.infoPlist.NSAppTransportSecurity.
 *   NSExceptionDomains`로 같은 두 도메인만 예외 처리돼 있다. 이 플러그인은 그
 *   대칭을 Android에 맞춘다.
 *
 * 전역 cleartext(`usesCleartextTraffic: true`)는 금지한다. 그러면 앱의 모든
 * 트래픽이 평문 다운그레이드에 노출된다. 대신 `res/xml/network_security_config.xml`
 * 의 `<domain-config>`로 두 도메인만 허용하고 나머지는 Android 기본(차단)을 남긴다.
 *
 * debug 소스셋 오버레이가 필요한 이유:
 * - Expo가 생성하는 `app/src/debug/AndroidManifest.xml`은 Metro(`http://<LAN-IP>:8081`)
 *   접속을 위해 `android:usesCleartextTraffic="true"`를 건다.
 * - 그런데 API 24+ 에서는 `android:networkSecurityConfig`가 있으면
 *   `usesCleartextTraffic`이 **무시**된다. 위 속성만 걸면 dev client가 Metro에
 *   붙지 못한다.
 * - 그래서 debug 소스셋에 같은 이름의 리소스를 하나 더 둔다. Android 리소스 병합은
 *   build-type(debug) > main 우선순위라, debug 빌드에서만 관대한 설정이 적용되고
 *   release 빌드는 main 의 두 도메인 한정 설정을 그대로 쓴다.
 *
 * 멱등성: manifest 속성은 대입(set), XML은 덮어쓰기(overwrite)라 여러 번 실행돼도
 * 중복·누적되지 않는다.
 */
const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const NETWORK_SECURITY_CONFIG_RESOURCE = '@xml/network_security_config';
const MAIN_RESOURCE_RELATIVE_PATH = 'app/src/main/res/xml/network_security_config.xml';
const DEBUG_RESOURCE_RELATIVE_PATH = 'app/src/debug/res/xml/network_security_config.xml';

/** HTTPS를 지원하지 않는 서울 열린데이터 API 호스트 (iOS ATS 예외와 동일 목록) */
const CLEARTEXT_DOMAINS = ['swopenapi.seoul.go.kr', 'openapi.seoul.go.kr'];

const MAIN_NETWORK_SECURITY_CONFIG_XML = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by plugins/withSeoulApiCleartext.js — do not edit by hand.
  Seoul Open API hosts do not support HTTPS, so cleartext is permitted for
  these domains only. Every other host keeps the Android default (blocked).
-->
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
${CLEARTEXT_DOMAINS.map((domain) => `        <domain includeSubdomains="true">${domain}</domain>`).join('\n')}
    </domain-config>
</network-security-config>
`;

const DEBUG_NETWORK_SECURITY_CONFIG_XML = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by plugins/withSeoulApiCleartext.js — do not edit by hand.
  Debug-only overlay: keeps Metro / local dev-server cleartext working, because
  android:usesCleartextTraffic (set by Expo's debug manifest) is ignored once a
  network security config exists. Release builds use the strict main variant.
-->
<network-security-config>
    <base-config cleartextTrafficPermitted="true" />
</network-security-config>
`;

/** `<application>`에 android:networkSecurityConfig 속성을 건다. */
const withNetworkSecurityConfigAttribute = (config) =>
  withAndroidManifest(config, (mod) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(mod.modResults);

    application.$['android:networkSecurityConfig'] = NETWORK_SECURITY_CONFIG_RESOURCE;

    return mod;
  });

const writeResourceAsync = async (platformProjectRoot, relativePath, contents) => {
  const filePath = path.join(platformProjectRoot, relativePath);

  await fs.promises.mkdir(path.dirname(filePath), { recursive: true });
  await fs.promises.writeFile(filePath, contents, 'utf8');
};

/** main(release 포함) + debug 소스셋의 network_security_config.xml 을 생성한다. */
const withNetworkSecurityConfigResource = (config) =>
  withDangerousMod(config, [
    'android',
    async (mod) => {
      const { platformProjectRoot } = mod.modRequest;

      await writeResourceAsync(
        platformProjectRoot,
        MAIN_RESOURCE_RELATIVE_PATH,
        MAIN_NETWORK_SECURITY_CONFIG_XML
      );
      await writeResourceAsync(
        platformProjectRoot,
        DEBUG_RESOURCE_RELATIVE_PATH,
        DEBUG_NETWORK_SECURITY_CONFIG_XML
      );

      return mod;
    },
  ]);

const withSeoulApiCleartext = (config) =>
  withNetworkSecurityConfigResource(withNetworkSecurityConfigAttribute(config));

module.exports = withSeoulApiCleartext;
