/**
 * fetchExitLandmarks — generator for src/data/exitLandmarks.json
 *
 * 국가철도공단_서울교통공사 출구별 주요 장소 CSV(data.go.kr 파일데이터)를 읽어
 * 역명 → 출구번호 → 시설명[] 의 컴팩트 정적 JSON 으로 변환한다. 출구 시설은
 * 거의 안 변하므로 데이터셋 갱신 시에만 재실행한다. `fetchStationAccessibility.ts`
 * 와 동일하게 정적 JSON 을 산출하는 빌드타임 스크립트.
 *
 * 컴팩트 구조: 엔트리마다 stationName(=그룹 키)·lineNum(미사용)을 중복 저장하지
 * 않고 출구번호→시설명[] 로만 적재한다. staticExitLandmarks 로더가 읽을 때
 * stationName·exitNumber 를 채워 ExitLandmark 로 복원한다 (번들 크기 절감).
 *
 * 데이터 출처 (Issue #173):
 *   data.go.kr → "국가철도공단_서울교통공사 출구별 주요 장소" (파일데이터, CSV).
 *   인코딩 EUC-KR(CP949), 컬럼: 철도운영기관,노선명,역명,출구번호,출구별주요시설명.
 *
 * 실행:
 *   npx ts-node scripts/fetchExitLandmarks.ts "<다운로드한 CSV 경로>"
 */

// 1회성 CLI 빌드 스크립트 — 진행 로그에 console 출력이 정상 동작이다
// (앱 번들 코드 아님). no-console 규칙은 이 파일에 한해 비활성화한다.
/* eslint-disable no-console */
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { TextDecoder } from 'util';

const CSV_COLUMNS = ['철도운영기관', '노선명', '역명', '출구번호', '출구별주요시설명'] as const;

interface SeoulStationsFile {
  readonly DATA: readonly { readonly station_nm: string }[];
}

/** 앱이 stationName 으로 쓰는 정식 역명 집합 (seoulStations.json). */
function loadAppStationNames(): Set<string> {
  const raw = readFileSync(join(__dirname, '../src/data/seoulStations.json'), 'utf8');
  const file = JSON.parse(raw) as SeoulStationsFile;
  return new Set(file.DATA.map((s) => s.station_nm));
}

/**
 * CSV 역명을 앱 stationName 포맷으로 정규화.
 *  1) 부역명 괄호 제거: "잠실(송파구청)" → "잠실"
 *  2) "역" 접미사는 떼었을 때 알려진 역이 될 때만 제거: "하남검단산역" → "하남검단산".
 *     ("서울역" 처럼 역이 정식 명칭의 일부인 경우는 유지 — seoulStations 에 그대로 존재.)
 */
function normalizeStationName(raw: string, appNames: Set<string>): string {
  const base = raw.replace(/\(.*\)\s*$/, '').trim();
  if (!appNames.has(base) && base.endsWith('역')) {
    const stripped = base.slice(0, -1);
    if (appNames.has(stripped)) return stripped;
  }
  return base;
}

/** 출구번호 정렬: 숫자 우선, 그 외는 문자열 비교. */
function compareExit(a: string, b: string): number {
  const na = Number.parseInt(a, 10);
  const nb = Number.parseInt(b, 10);
  if (Number.isNaN(na) || Number.isNaN(nb)) return a.localeCompare(b, 'ko');
  return na - nb;
}

function main(): void {
  const csvPath = process.argv[2];
  if (!csvPath) {
    console.error('사용법: npx ts-node scripts/fetchExitLandmarks.ts "<CSV 경로>"');
    process.exit(1);
  }

  const appNames = loadAppStationNames();
  const text = new TextDecoder('euc-kr').decode(readFileSync(csvPath));
  const lines = text.split(/\r?\n/).filter((l) => l.length > 0);

  const header = lines[0]?.split(',').map((c) => c.trim()) ?? [];
  if (!CSV_COLUMNS.every((col, i) => header[i] === col)) {
    console.error(`예상 컬럼과 다릅니다. expected=${CSV_COLUMNS.join(',')} got=${header.join(',')}`);
    process.exit(1);
  }

  // 역명 → 출구번호 → 시설명[]
  const stations: Record<string, Record<string, string[]>> = {};
  let skipped = 0;
  let facilityCount = 0;
  for (let i = 1; i < lines.length; i++) {
    const cols = lines[i]!.split(',');
    if (cols.length < 5) { skipped++; continue; }
    const stationName = normalizeStationName(cols[2]!, appNames);
    const exitNumber = cols[3]!.trim();
    const landmarkName = cols[4]!.trim();
    if (!stationName || !exitNumber || !landmarkName) { skipped++; continue; }
    const byExit = (stations[stationName] ??= {});
    (byExit[exitNumber] ??= []).push(landmarkName);
    facilityCount++;
  }

  // 결정적 diff: 역명(ko) + 출구번호(숫자) 정렬.
  const sortedStations: Record<string, Record<string, string[]>> = {};
  for (const name of Object.keys(stations).sort((a, b) => a.localeCompare(b, 'ko'))) {
    const byExit = stations[name]!;
    const sortedByExit: Record<string, string[]> = {};
    for (const exit of Object.keys(byExit).sort(compareExit)) {
      sortedByExit[exit] = byExit[exit]!;
    }
    sortedStations[name] = sortedByExit;
  }

  const stationCount = Object.keys(sortedStations).length;
  console.log(`변환 완료: ${facilityCount} 시설 / ${stationCount} 역 (skip ${skipped})`);

  const out = {
    generatedAt: new Date().toISOString(),
    source:
      '국가철도공단_서울교통공사 출구별 주요 장소 (data.go.kr 파일데이터, CSV). ' +
      'Generated by scripts/fetchExitLandmarks.ts',
    stations: sortedStations,
  };

  const outPath = join(__dirname, '../src/data/exitLandmarks.json');
  writeFileSync(outPath, `${JSON.stringify(out, null, 2)}\n`, 'utf8');
  console.log(`기록 완료: ${outPath}`);
}

main();
