/**
 * fetchExitLandmarks — one-off generator for src/data/exitLandmarks.json
 *
 * 국가철도공단_출구별주요장소 API(odcloud 15073460)의 전체 데이터셋을 내려받아
 * 역명별로 그룹화해 정적 JSON 으로 베이크한다. 출구 주요장소는 거의 안 변하므로
 * 가끔만 재실행한다. `scripts/fetchStationAccessibility.ts` 와 동일한 패턴.
 *
 * 사전 준비 (Issue #173):
 *   이 API 는 data.go.kr 에서 데이터셋(15073460)별 "활용신청"(서비스 등록)이
 *   필요하다. 등록되지 않은 키로 호출하면 HTTP 400 {"code":-3,"msg":"등록되지
 *   않은 서비스 입니다."} 가 반환된다. data.go.kr 에서 해당 데이터셋을 활용신청한
 *   serviceKey 를 EXPO_PUBLIC_DATA_PORTAL_API_KEY 에 넣은 뒤 실행할 것.
 *
 * 실행:
 *   EXPO_PUBLIC_DATA_PORTAL_API_KEY=<registered-key> npx ts-node scripts/fetchExitLandmarks.ts
 *
 * 네트워크: api.odcloud.kr 는 sandbox allowlist 에 없다 — sandbox 해제 또는
 * 일반 터미널에서 실행할 것.
 */

// 1회성 CLI 빌드 스크립트 — 진행 로그·경고에 console 출력이 정상 동작이다
// (앱 번들 코드 아님). no-console 규칙은 이 파일에 한해 비활성화한다.
/* eslint-disable no-console */
import { writeFileSync } from 'fs';
import { join } from 'path';
import {
  ExitLandmark,
  ExitLandmarkRawData,
  parseLandmarkCategory,
} from '../src/models/publicData';

const API_KEY = process.env.EXPO_PUBLIC_DATA_PORTAL_API_KEY ?? '';
const ENDPOINT =
  'https://api.odcloud.kr/api/15073460/v1/uddi:5e336c4a-7f38-4429-b815-e1c31c0a6c46';
const PER_PAGE = 1000;
const RATE_LIMIT_MS = 300; // odcloud 페이지 간 여유

interface OdcloudResponse {
  readonly currentCount?: number;
  readonly matchCount?: number;
  readonly totalCount?: number;
  readonly data?: readonly ExitLandmarkRawData[];
}

const sleep = (ms: number): Promise<void> =>
  new Promise((resolve) => setTimeout(resolve, ms));

/** 전체 데이터셋을 페이지네이션으로 모두 수집. */
async function fetchAllRows(): Promise<ExitLandmarkRawData[]> {
  const all: ExitLandmarkRawData[] = [];
  let page = 1;

  for (;;) {
    const url = new URL(ENDPOINT);
    url.searchParams.append('serviceKey', decodeURIComponent(API_KEY));
    url.searchParams.append('page', String(page));
    url.searchParams.append('perPage', String(PER_PAGE));

    const res = await fetch(url.toString(), { headers: { Accept: 'application/json' } });
    if (!res.ok) {
      const body = await res.text();
      throw new Error(`HTTP ${res.status} ${res.statusText}: ${body.slice(0, 200)}`);
    }

    const json = (await res.json()) as OdcloudResponse;
    const rows = json.data ?? [];
    all.push(...rows);

    const total = json.totalCount ?? all.length;
    console.log(`  page ${page}: +${rows.length} rows (${all.length}/${total})`);

    if (rows.length === 0 || all.length >= total) break;
    page += 1;
    await sleep(RATE_LIMIT_MS);
  }

  return all;
}

/** 원시 행을 역명별 ExitLandmark[] 로 그룹화. */
function groupByStation(rows: readonly ExitLandmarkRawData[]): Record<string, ExitLandmark[]> {
  const stations: Record<string, ExitLandmark[]> = {};
  for (const raw of rows) {
    const name = raw.역명;
    if (!name) continue;
    const landmark: ExitLandmark = {
      stationCode: raw.역번호,
      stationName: raw.역명,
      lineNum: raw.호선,
      exitNumber: raw.출구번호,
      landmarkName: raw.주요장소,
      category: parseLandmarkCategory(raw.장소분류 || ''),
    };
    (stations[name] ??= []).push(landmark);
  }
  return stations;
}

async function main(): Promise<void> {
  if (!API_KEY) {
    console.error('EXPO_PUBLIC_DATA_PORTAL_API_KEY 미설정');
    process.exit(1);
  }

  console.log('국가철도공단 출구별주요장소 전체 수집 중...');
  const rows = await fetchAllRows();
  const stations = groupByStation(rows);

  const stationCount = Object.keys(stations).length;
  console.log(`수집 완료: ${rows.length} rows → ${stationCount} 역`);

  const out = {
    generatedAt: new Date().toISOString(),
    source:
      '국가철도공단_출구별주요장소 (data.go.kr / odcloud 15073460). ' +
      'Generated by scripts/fetchExitLandmarks.ts',
    stations,
  };

  const outPath = join(__dirname, '../src/data/exitLandmarks.json');
  writeFileSync(outPath, `${JSON.stringify(out, null, 2)}\n`, 'utf8');
  console.log(`기록 완료: ${outPath}`);
}

main().catch((err) => {
  console.error('fetchExitLandmarks 실패:', err instanceof Error ? err.message : err);
  process.exit(1);
});
