#!/usr/bin/env node
/**
 * Generate the full station-id -> docs/subway_line.svg coordinate table.
 *
 * The current SVG export has no semantic station ids, so verified SVG points
 * are merged over the existing schematic projection. This removes runtime
 * "only some stations have anchors" behavior while keeping manual SVG fixes in
 * one reproducible place.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const STATIONS_PATH = resolve(ROOT, 'src/data/stations.json');
const OUT_PATH = resolve(ROOT, 'src/components/map/subwayLineSvgAnchorTable.ts');

const SVG_MAP_WIDTH = 1525;
const SVG_MAP_HEIGHT = 1000;
const SOURCE_MAP_WIDTH = 4900;
const SOURCE_MAP_HEIGHT = 4400;

const verifiedAnchorsById = {
  // 7호선 서쪽 구간은 docs/subway_line.svg의 역점 좌표를 직접 사용한다.
  s_3763: { x: 40, y: 580 }, // 석남
  s_ec82b0ea: { x: 100, y: 605 }, // 산곡
  bupyeong_gu: { x: 140, y: 605 }, // 부평구청
  s_eab5b4ed: { x: 195, y: 550 }, // 굴포천
  s_3759: { x: 210, y: 535 }, // 삼산체육관
  s_ec8381eb: { x: 210, y: 515 }, // 상동
  s_ebb680ec: { x: 240, y: 495 }, // 부천시청
  s_3756: { x: 270, y: 500 }, // 신중동
  s_ecb698ec: { x: 285, y: 515 }, // 춘의
  s_3754: { x: 290, y: 542.5 }, // 부천종합운동장
  s_eab98cec: { x: 290, y: 565 }, // 까치울
  s_1821: { x: 325, y: 600 }, // 온수
  s_ecb29cec: { x: 340, y: 615 }, // 천왕
  gwangmyeong_sageo: { x: 355, y: 630 }, // 광명사거리
  cheolsan: { x: 390, y: 640 }, // 철산
  gasan_digital: { x: 415, y: 640 }, // 가산디지털단지
};

const formatNumber = (value) => {
  const fixed = value.toFixed(2);
  return fixed.replace(/\.00$/, '').replace(/(\.\d)0$/, '$1');
};

const formatPoint = ({ x, y }) => `{ x: ${formatNumber(x)}, y: ${formatNumber(y)} }`;

const projectStation = (station) => ({
  x: (station.x / SOURCE_MAP_WIDTH) * SVG_MAP_WIDTH,
  y: (station.y / SOURCE_MAP_HEIGHT) * SVG_MAP_HEIGHT,
});

const stations = JSON.parse(readFileSync(STATIONS_PATH, 'utf8'));
const entries = Object.values(stations)
  .sort((a, b) => a.id.localeCompare(b.id))
  .map((station) => {
    const point = verifiedAnchorsById[station.id] ?? projectStation(station);
    return `  ${JSON.stringify(station.id)}: ${formatPoint(point)}, // ${station.name}`;
  });

const content = `/**\n * Generated by scripts/generateSubwayLineSvgAnchors.mjs.\n * Do not edit by hand; add verified overrides in the generator and rerun it.\n */\n\nexport const SUBWAY_LINE_SVG_ANCHORS_BY_ID = {\n${entries.join('\n')}\n} as const;\n`;

writeFileSync(OUT_PATH, content);
// eslint-disable-next-line no-console
console.log(`Wrote ${entries.length} subway SVG anchors to ${OUT_PATH}`);
